First stage of type checking completed successfully with 0 warnings

While type checking, exception was thrown :

line 6 :
  or a 1

Unexpected argument type, int was expected, list found.
