First stage of type checking completed successfully with 0 warnings

While type checking, exception was thrown :

line 4 :
  and a b

Unexpected argument type, int was expected, list found.
