
While executing code, exception was thrown :

line 19 :
  output (sum [6 11 3]) 6 + 11 + 3 =

Output must have two argument.
